# Generated by Django 5.1.3 on 2026-02-24 08:36

import providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=providers.models.provider_image_upload_to),
        ),
    ]
